### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by legoboyvdlp** [JSBSim-Team/jsbsim#134]
Severity	Code	Description	Project	File	Line	Suppression State
Error		command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\link.exe' failed with exit status 1120	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CMakeLists.txt	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\EXEC	1	

Hi,
While trying to build following https://jsbsim-team.github.io/jsbsim-reference-manual/mypages/quickstart-building-using-visualstudio/, I got this error. Does anyone know of any solution? 

Thanks,
Jonathan

Edit: I'll try building Release-x64, not Debug, and see if that helps...

The Release build worked perfectly.
Sorry, maybe this is not the place for build failure reports, but if it is something I did wrong with debug, then I'd like to find out ;)

**Comment by seanmcleod** [comment]
A while back I remember having an issue in terms of building a debug version if I tried to build all targets via CMake. The issue was because the linker was looking for a debug version of the Python dll when building a debug version of our JSBSim Python wrapper and at least on my machine my installation of Python didn't have a debug version of the Python dll.

So I typically build a release version of the JSBSim-Python wrapper and just build a debug version of the JSBSim executable if I want to debug anything within JSBSim.

**Comment by legoboyvdlp** [comment]
May as well close now...

**Comment by bcoconni** [comment]
Closed as per @legoboyvdlp feedback.
