### ISSUE TITLE
How to start the R22 helicopter?

### ISSUE THREAD

**Issue by tilongzs** [JSBSim-Team/jsbsim#205]
I downloaded the R22 helicopter ([https://github.com/NikolaiVChr/Robinson](https://github.com/NikolaiVChr/Robinson)), which works well in Flight Gear. But when I loaded it with JSBSim, I couldn't turn the main rotor and the engine didn't work. In the output CSV table, the output value /rotors/main/rpm is less than 10, and the system/electrical/starter-norm is 0 instead of the 1 I set.
Thanks.

set aircraftname=R22
set  resetname=reset00
 
JSBSim --aircraft=\%aircraftname% --initfile=%resetname%^
 --outputlogfile=runJSBSim_withAircraft_%aircraftname%.csv --simulation-rate=200  --end=1000^
 --property=fcs/throttle-cmd-norm=1.0^
 --property=propulsion/magneto_cmd=1^
 --property=propulsion/starter_cmd=1^
 --property=fcs/left-brake-cmd-norm=0^
 --property=fcs/right-brake-cmd-norm=0^
 --property=fcs/center-brake-cmd-norm=0^
 --property=systems/electrical/starter-norm=1^
 --property=/engines/engine/n1=1^
 > runJSBSim_withAircraft_%aircraftname%.log

pause

**Comment by bcoconni** [comment]
I think the first course of action would be to open an issue at [the R22 project](https://github.com/NikolaiVChr/Robinson), and ask @NikolaiVChr 

Then, If you come to the conclusion with @NikolaiVChr that the R22 is not working with JSBSim standalone because of an error in JSBSim, then open an issue here.
