### ISSUE TITLE
Replace remaining 15 exit calls from FGXMLElement.cpp with matching exceptions

### ISSUE THREAD

**Issue by sthagen** [JSBSim-Team/jsbsim#312]
Libraries calling `exit` are less well to integrate. Commit 422910b6843baed4099f825c54d84d1e4df8fa0e already replaced the `exit` call in `FGXMLParser.cpp` with a bare `throw`.

I suggest to replace the 15 occurrences of `exit` calls in `FGXMLElement.cpp` with throws of matching exceptions from `std::exception` as a service for library users. An example would be [std::domain_error](https://en.cppreference.com/w/cpp/error/domain_error) in case the value is specifically out of the expected domain. Another would be [std::invalid_argument](https://en.cppreference.com/w/cpp/error/invalid_argument) if value is more broadly unexpected/invalid.

If no one objects I may very well provide a minimal invasive pull request this week.

**Comment by bcoconni** [comment]
Interestingly enough, I recently came across Herb Sutter's talk at CppCon2019 where (among other things) he suggests that exceptions should only be used for recoverable errors (i.e. errors for which the code can take actions and continue safely from there). I found he made a very interesting point.

![Herb Sutter talk at CppCon2019](https://user-images.githubusercontent.com/7502904/89421252-15121800-d734-11ea-99b5-1c8c771d7d20.png)

[The video can be viewed on YouTube](https://youtu.be/ARYP83yNAWk)

So yes, your proposal is interesting but I would suggest that for each `exit` call that you replace, you consider whether we should throw an exception, use an assertion, or brutally terminate the program. I am in complete agreement with you that exiting is not the proper way to handle errors for a library like JSBSim and that we should always give the opportunity to the client to quit properly. However as Herb Sutter explains in his presentation, it is very unlikely that the client will be able to recover from fatal errors anyway: for example, out of memory errors will most likely lead the OS to terminate the program even before the client has had a chance to display a nice dialog (because the dialog most likely needs to reserve some memory to display itself... but we already ran out of memory).

I guess we need to use our best judgement for each case and I am eager to have a discussion about  what are the best options to replace `exit` calls.

**Comment by sthagen** [comment]
Thanks a lot for the feedback and additional information as well as perspective.

Looking forward to these discussions and changes. My perspective is w.r.t. these opaque exits (from a library client perspective). Imagine some use case, where this library is only a part of a larger simulation program that might allow the operators of that program to edit xml configuration files. When these xml files are not at all or only partially as expected by the jsbsim parser, this may in itself not be a problem for the whole program, as maybe only one aspect is not working as intended. Currently I assume the behavior is, that the embedding program may not even start anymore as a whole, thus the jsbsim library is breaking an optional contract by killing the client or maybe that is not a use case for the jsbsim community (I am kind of inhabiting an ivory tower here 🗼 ).

I will take a look at the info provided by @bcoconni  and will inspect the cases at hand as well as  provide some code suggestions.

That being said, I still consider at least some of these exit calls as a bug (from a library perspective when assuming one use case as jsbsim functionality being an optional enhancement for the caller/embedding code).

**Comment by bcoconni** [comment]
> [...] When these xml files are not at all or only partially as expected by the jsbsim parser, this may in itself not be a problem for the whole program, as maybe only one aspect is not working as intended.

Yes malformed XML is the typical case where an exception should be thrown at least to give the user an opportunity to fix the XML file and re-submit it.
>  Currently I assume the behavior is, that the embedding program may not even start anymore as a whole, thus the jsbsim library is breaking an optional contract by killing the client or maybe that is not a use case for the jsbsim community

Proper error handling is indeed what is expected by larger applications that embed JSBSim such as FlightGear. I have to say that we have not had much complaints thus far about the current behaviour of JSBSim (by no means does that mean we cannot or should not improve) but I think this is due to FlightGear own limitations: it is not able to recover from an exception thrown by JSBSim and in most cases its course of action is to display a nice dialog box with JSBSim error message and a single 'Close' button. Anyway that is much better than JSBSim suddenly killing FlightGear as you mentioned, especially since Windows users tend not to use the console/shell and will not see the message issued by JSBSim.

Actually complaints are more about errors that are silently swallowed by JSBSim and that lead to unexpected behaviours. There are currently a lot of occurrences in the code where JSBSim make a decision without displaying a message (neither information nor warning or error). I am trying to fix them as I am coming across them but I have never reviewed the complete code base to find and address all of them. Anyway, that is a topic for another issue.

In addition, there is more than exceptions: assertions are an interesting tool to check internal errors. I have recently used them (commit 31862e12c7324b0471a869fbfa0c734f9c87da23) to make sure that some methods of `FGLocation` are not used if `FGLocation::SetEllipse` has not been called beforehand. In that particular case, if the assertion fails that means that we have an internal error, something that neither the library client nor the user can handle. One nice thing about assertions is that they are ignored when compiling the release code with the `NDEBUG` flag so we get safeguards that generate no extra code for releases.

**Comment by sthagen** [comment]
After some reflection on the arguments found in the talk by Herb Sutter and the discussion here, I came to the following conclusion (of course only for myself) for the most useful perspective on the shared programming model:

> We are not really handling pure C++ compiled into a binary from these interface modules but instead our error branches are the only entity that can deal with the extended dynamic programming of a user providing XML data as input that does not match our compiled data model.

So, in this case to me `logic_error` kind exceptions are stating exactly the right fact: The programmer did wrong. The programmer here is the data provider. Also the definition of "call site" might include the XML data file which triggers the parsing and because we cannot place error handling or contract enforcement in every XML file modification at runtime site, I consider the use of exceptions in our compiled code the ideal middle ground (as a library).

Sorry for any clumsy wording - I just hope my reasoning became explicit and is a useful perspective.
