### ISSUE TITLE
Problem with stall warning

### ISSUE THREAD

**Issue by eeeewwqq** [JSBSim-Team/jsbsim#790]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => **Please do not submit support request here**, see note at the top of this template.

**Describe the issue**
systems/stall-warn-norm and aero/stall-hyst-norm doesn't seem to be working for some aircrafts. I put plane at some altitude above ground with zero speed and velocities and I was able to get stall warn only for c172x. It doesn't work for global5000 and f104 models. + I tried some 3d-party models and it doesn't work as well. 

Could someone help?

**What is the current behavior?**
global5000 and f104 systems/stall-warn-norm=0 aero/stall-hyst-norm=0

**What is the expected behavior?**
global5000 and f104 systems/stall-warn-norm>0 aero/stall-hyst-norm=1

**Please tell us about your environment:**

 - OS: Windows
 - JSBSim version: 1.2.0
 - Language: Unity + JSBSim compiled as dll

Output examples
[f104.csv](https://github.com/JSBSim-Team/jsbsim/files/10298817/f104.csv)
[c172x.csv](https://github.com/JSBSim-Team/jsbsim/files/10298818/c172x.csv)
[global5000.csv](https://github.com/JSBSim-Team/jsbsim/files/10298820/global5000.csv)

**Comment by seanmcleod** [comment]
That's because the author of the aircraft's FDM needs to provide data for `alphalimits` and `hysteresis_limits` and these aren't compulsory/required data. So you will only get meaningful output for the properties if the required input data is supplied.

https://github.com/JSBSim-Team/jsbsim/blob/a919d4dd6fd7ba696d21e2c7f25cb35ceb670982/src/models/FGAerodynamics.cpp#L347-L361

https://github.com/JSBSim-Team/jsbsim/blob/a919d4dd6fd7ba696d21e2c7f25cb35ceb670982/src/models/FGAerodynamics.cpp#L163-L177

**Comment by eeeewwqq** [comment]
Thanks
